version: "3.6"

services:

  # Must be executed with a flag "--env-file" to the environment to run
  swagger-client-repo-gen:
    # https://github.com/intuit/unmazedboot/releases/tag/v0.5.0
    image: marcellodesales/swagger-client-package-repo-gen
    build:
      context: .
    environment:
      SCHEMA_FILE_NAME: ${SCHEMA_FILE_NAME:-swagger.json}
      GENERATE_CLIENT_LANG: ${GENERATE_CLIENT_LANG:-java}
      GENERATE_CLIENT_WITH_LIBRARY: ${GENERATE_CLIENT_WITH_LIBRARY}
      GENERATE_CLIENT_GROUPID: ${GENERATE_CLIENT_GROUPID:-com.example.package}
      GENERATE_CLIENT_ARTIFACT: ${GENERATE_CLIENT_ARTIFACT:-service-artifac}
      GENERATE_CLIENT_VERSION: ${GENERATE_CLIENT_VERSION:-0.1.0-SNAPSHOT}
      GENERATE_CLIENT_MODEL_PACKAGE: ${GENERATE_CLIENT_MODEL_PACKAGE:-$GENERATE_CLIENT_GROUPID-model}
      GENERATE_CLIENT_API_PACKAGE: ${GENERATE_CLIENT_API_PACKAGE:-$GENERATE_CLIENT_GROUPID-api}
      GENERATE_CLIENT_INVOKER_PACKAGE: ${GENERATE_CLIENT_INVOKER_PACKAGE:-$GENERATE_CLIENT_GROUPID.invoker}
      GENERATE_CLIENT_URL: ${GENERATE_CLIENT_URL:-https://gitlab.com/org/group/repo}
      GENERATE_CLIENT_GIT_HOST: ${GENERATE_CLIENT_GIT_HOST:-gitlab.com}
      GENERATE_CLIENT_GIT_USER_REPO: ${GENERATE_CLIENT_GIT_USER_REPO:-org/group/repo}
      GENERATE_CLIENT_GITLAB_PROJECT_ID: ${GENERATE_CLIENT_GITLAB_PROJECT_ID}
      GENERATE_CLIENT_AUTHOR_FULLNAME: ${GENERATE_CLIENT_AUTHOR_FULLNAME:-Marcello de Sales}
      GENERATE_CLIENT_AUTHOR_EMAIL: ${GENERATE_CLIENT_AUTHOR_EMAIL:-marcello.desales@example.com}
      GENERATE_CLIENT_PUBLISH_TOKEN: ${GENERATE_CLIENT_PUBLISH_TOKEN}
      GENERATE_CLIENT_GIT_BRANCH: ${GENERATE_CLIENT_GIT_BRANCH}
      GENERATE_CLIENT_GIT_PUSH: ${GENERATE_CLIENT_GIT_PUSH}
    volumes:
       # The schemas dir with the files where SCHEMA_FILE_NAME is found
       - ".:/schemas"

       # Where the generated client stubs are located
       - "./client-api:/client-api"

       # When providing GENERATE_CLIENT_PUBLISH_TOKEN, both the library and source are pushed
       # Needs the SSH keys to push the code automagically
       - ${HOME}/.ssh:/root/.ssh
