#!/bin/bash

# Most variables are from https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen-maven-plugin/README.md

: ${SCHEMA_FILE_NAME?"Must set SCHEMA_FILE_NAME"}

if [ ! -f "/schemas/${SCHEMA_FILE_NAME}" ]; then
  echo "The schema filename ${SCHEMA_FILE_NAME} does NOT exist! Please mount /schemas with it!"
  exit 1
fi

: ${GENERATE_CLIENT_LANG?"Must GENERATE_CLIENT_LANG"}
: ${GENERATE_CLIENT_WITH_LIBRARY?"Must set GENERATE_CLIENT_WITH_LIBRARY"}

: ${GENERATE_CLIENT_GROUPID?"Must set GENERATE_CLIENT_GROUPID"}
: ${GENERATE_CLIENT_ARTIFACT?"Must set GENERATE_CLIENT_ARTIFACT"}
: ${GENERATE_CLIENT_VERSION?"Must set GENERATE_CLIENT_VERSION"}

# Packages where the source-code will be created
: ${GENERATE_CLIENT_MODEL_PACKAGE?"Must set GENERATE_CLIENT_MODEL_PACKAGE"}
: ${GENERATE_CLIENT_API_PACKAGE?"Must set GENERATE_CLIENT_API_PACKAGE"}
: ${GENERATE_CLIENT_INVOKER_PACKAGE?"Must set GENERATE_CLIENT_INVOKER_PACKAGE"}

: ${GENERATE_CLIENT_URL?"Must set GENERATE_CLIENT_URL"}
: ${GENERATE_CLIENT_GIT_HOST?"Must set GENERATE_CLIENT_GIT_HOST"}

# https://stackoverflow.com/questions/2829613/how-do-you-tell-if-a-string-contains-another-string-in-posix-sh/8811800#8811800
if test "${GENERATE_CLIENT_GIT_HOST#*gitlab}" != "gitlab"; then
  : ${GENERATE_CLIENT_GITLAB_PROJECT_ID?"Must set GENERATE_CLIENT_GITLAB_PROJECT_ID for gitlab hosts. It's in the root of the repo project!"}
fi

: ${GENERATE_CLIENT_GIT_USER_REPO?"Must set GENERATE_CLIENT_GIT_USER_REPO"}

# For Developer Info and Initial Commit
: ${GENERATE_CLIENT_AUTHOR_FULLNAME?"Must set GENERATE_CLIENT_AUTHOR_FULLNAME"}
: ${GENERATE_CLIENT_AUTHOR_EMAIL?"Must set GENERATE_CLIENT_AUTHOR_EMAIL"}

# Normalize clients that doesn't have library
if [ -z "${GENERATE_CLIENT_WITH_LIBRARY}" ]; then
  export GENERATE_CLIENT_TYPE=${GENERATE_CLIENT_LANG}
else
  export GENERATE_CLIENT_TYPE=${GENERATE_CLIENT_WITH_LIBRARY}
fi

# Where to send the files to
export GIT_REMOTE="git@${GENERATE_CLIENT_GIT_HOST}:${GENERATE_CLIENT_GIT_USER_REPO}-${GENERATE_CLIENT_TYPE}.git"

echo ""
echo "🐙 Setting up initial git repo at '${GIT_REMOTE}'"
echo ""
echo "- Setting user as ${GENERATE_CLIENT_AUTHOR_FULLNAME}"

git config --global user.name "${GENERATE_CLIENT_AUTHOR_FULLNAME}"
echo "- Setting email as ${GENERATE_CLIENT_AUTHOR_EMAIL}"

git config --global user.email "${GENERATE_CLIENT_AUTHOR_EMAIL}"

if [ -z ${GENERATE_CLIENT_GIT_BRANCH} ]; then
  export GENERATE_CLIENT_GIT_BRANCH=master
fi

export CLIENT_API_LOCATION=/generator/client-api

echo "- Attempt to pull existing Git Repo origin ${GIT_REMOTE} at branch ${GENERATE_CLIENT_GIT_BRANCH}..."
# Attempt to clone the repo in the given branch
git clone --progress --branch ${GENERATE_CLIENT_GIT_BRANCH} ${GIT_REMOTE} ${CLIENT_API_LOCATION} 2> git-clone.log

# Verify if it was cloned or needs to create a new one
if grep -q "fatal: Remote branch ${GENERATE_CLIENT_GIT_BRANCH} not found in upstream origin" "git-clone.log"; then
  echo "- WARNING: Cloning main branch as the repo does not have the requested branch ${GENERATE_CLIENT_GIT_BRANCH}"
  git clone --progress ${GIT_REMOTE} ${CLIENT_API_LOCATION} 2> git-clone-main.log

  # Not empty
  if grep -q "You appear to have cloned an empty repository" "git-clone-main.log"; then
    echo "- Pulled main branch origin ${GIT_REMOTE}"
    echo "- Creating requested branch ${GENERATE_CLIENT_GIT_BRANCH}"
    git -C ${CLIENT_API_LOCATION} checkout -b ${GENERATE_CLIENT_GIT_BRANCH}
    export CREATE_NEW_GIT_REPO=true

  else
    echo "- Pulled existing Git Repo origin ${GIT_REMOTE} from branch ${GENERATE_CLIENT_GIT_BRANCH}"
  fi

elif grep -q "fatal: Could not read from remote repository" "git-clone.log"; then
  # Create a new repo because the repo does not exist
  mkdir ${CLIENT_API_LOCATION}

  git init ${CLIENT_API_LOCATION}

  # The git-remote.txt is generated by the update python
  git -C ${CLIENT_API_LOCATION} remote add origin ${GIT_REMOTE}

  # Create a new branch
  git -C ${CLIENT_API_LOCATION} checkout -b ${GENERATE_CLIENT_GIT_BRANCH}

  export CREATE_NEW_GIT_REPO=true
  # When the clone worked and the repo exists, not empty

  echo "- Initializing Git Repo at origin ${GIT_REMOTE} at branch ${GENERATE_CLIENT_GIT_BRANCH}"
else
  echo "- Pulled existing Git Repo origin ${GIT_REMOTE} from branch ${GENERATE_CLIENT_GIT_BRANCH}"
fi

# Generate the sources, containing springboot, sources, etc repo
echo ""
if [ ! -z "${GENERATE_CLIENT_WITH_LIBRARY}" ]; then
  echo "👽 Generate sources from ${SCHEMA_FILE_NAME} in ${GENERATE_CLIENT_LANG} using library ${GENERATE_CLIENT_WITH_LIBRARY}"
else
  echo "👽 Generate sources from ${SCHEMA_FILE_NAME} in ${GENERATE_CLIENT_LANG}"
fi
echo ""

# Generates the files under the dir springboot-client-api/
mvn generate-sources --offline

if [ "${GENERATE_CLIENT_LANG}" == "java" ]; then
  if [ -z ${GENERATE_CLIENT_GIT_BRANCH} ]; then
    echo ""
    echo "🏗  Updating client metadata and files for CI/CD for ${GENERATE_CLIENT_LANG}"
    python handler/java/maven-updater.py

  else
    echo ""
    echo "🏗  Updating client metadata already setup and in the repo!"
  fi
fi

echo ""
echo "🏺 Packaging clients from stubs"
echo ""
if [ "$GENERATE_CLIENT_LANG" == "java" ]; then
  cd ${CLIENT_API_LOCATION}
  mvn package -Dmaven.test.skip=true

  # Fix the Android thing that's added
  # if [ -z "${GENERATE_CLIENT_FOR_ANDROID}" ]; then
  #   find src -name AndroidManifest.xml  | xargs rm -f
  # fi
  cd ..

elif [ "$GENERATE_CLIENT_LANG" == "dart" ]; then
  echo "Dart package is the git repo itself..."
fi

git -C ${CLIENT_API_LOCATION} status > git-status.log
if grep -q "Your branch is up to date" "git-status.log"; then
  echo "* Nothing to update as there are no changes..."
  echo "Aborting..."
  exit 0
fi

echo ""
echo "🎨 Copying originating schema '/schemas/${SCHEMA_FILE_NAME}'"
echo ""
if [ "$GENERATE_CLIENT_LANG" == "java" ]; then
  export SCHEMA_LOCATION="${CLIENT_API_LOCATION}/src/main/resources"
fi

if [ "$GENERATE_CLIENT_LANG" == "dart" ]; then
  export SCHEMA_LOCATION="${CLIENT_API_LOCATION}/assets"
fi

# Copying the schema to the location
# Copy the file to the resources named "swagger-api.[ext]"
mkdir -p ${SCHEMA_LOCATION}
export SCHEMA_EXT="${SCHEMA_FILE_NAME##*.}"
echo "Copying schemas to language location..."
cp -v "/schemas/${SCHEMA_FILE_NAME}" "${SCHEMA_LOCATION}/swagger-api.${SCHEMA_EXT}"

if [ ! -z ${CREATE_NEW_GIT_REPO} ]; then
  echo "- Initial commit..."
  git -C ${CLIENT_API_LOCATION} add .

  # https://stackoverflow.com/questions/5064563/add-line-break-to-git-commit-m-from-the-command-line/5064653#5064653
  git -C ${CLIENT_API_LOCATION} commit --no-edit -F- <<EOF
:tada:  Initial commit for client API

* Generated on $(date -d now)"
* By ${GENERATE_CLIENT_AUTHOR_FULLNAME} <${GENERATE_CLIENT_AUTHOR_EMAIL}>
* From: src/main/resources/${SCHEMA_FILE_NAME}
EOF

else
  echo ""
  echo "- Seeing the differences"
  git -C ${CLIENT_API_LOCATION} --no-pager diff

  # Just add all the changes to be committed
  git -C ${CLIENT_API_LOCATION} add .

  echo ""
  echo "- Update commit..."
  # https://stackoverflow.com/questions/5064563/add-line-break-to-git-commit-m-from-the-command-line/5064653#5064653
  git -C ${CLIENT_API_LOCATION} commit --no-edit -F- <<EOF
:new:  Updating client API

* Generated on $(date -d now)"
* By ${GENERATE_CLIENT_AUTHOR_FULLNAME} <${GENERATE_CLIENT_AUTHOR_EMAIL}>
* From: src/main/resources/${SCHEMA_FILE_NAME}
EOF
fi

echo ""
if [ ! -z "${GENERATE_CLIENT_PUBLISH_TOKEN}" ]; then
  export GITLAB_TOKEN=${GENERATE_CLIENT_PUBLISH_TOKEN}
  echo "📦 Publishing stubs to Gitlab Maven Repository"
  echo ""
  # https://docs.gitlab.com/12.10/ee/user/packages/maven_repository/#uploading-packages
  cd ${CLIENT_API_LOCATION}
  mvn deploy -s personal_settings.xml -Dmaven.test.skip=true
  cd ..

else
  echo "📦 Skip publishing stubs to Maven repo. Set GENERATE_CLIENT_PUBLISH_TOKEN=token if needed!"
fi
echo ""

if [ ! -z "${GENERATE_CLIENT_GIT_PUSH}" ]; then
  # let's just push as we pushed the modules
  echo "🚚 Pushing the code to the git host. Make sure to have the ssh keys mounted!"
  git -C ${CLIENT_API_LOCATION} push origin ${GENERATE_CLIENT_GIT_BRANCH}

else
  echo "🚚 Skip pushing to the code to git. Set GENERATE_CLIENT_GIT_PUSH=true if needed!"
fi
echo ""

# Finally, copy the generated artifacts to the client
export CLIENT_DIR="$GENERATE_CLIENT_ARTIFACT-${GENERATE_CLIENT_WITH_LIBRARY}"
if [ -d "/client-api/${CLIENT_DIR}" ]; then
  echo ""
  echo "💥 Deleting previous build from directory '/client-api/${CLIENT_DIR}'"
  echo ""
  rm -rf /client-api/${CLIENT_DIR}
fi
cd ..
mv ${CLIENT_API_LOCATION} ${CLIENT_DIR}

echo ""
echo "🍻 Local deploy to /client-api/${CLIENT_DIR}"
echo ""
cp -R -v ${CLIENT_DIR}/ /client-api

echo ""
echo "✨ Done!"
echo ""
